### ISSUE TITLE
Gazebo Test Model

### ISSUE THREAD

**Issue by a-tab-a** [llanesc/lqr-tracking#1]
Hello,

I was curious if you have any example code to apply the controller in gazebo quadrotor model? I see you mentioned testing it in gazebo.
Thanks

**Comment by llanesc** [comment]
I used PX4 software in the loop for simulations (https://dev.px4.io/v1.9.0/en/simulation/). You will need to clone the PX4 repo and build >> make px4_sitl gazebo_solo. Then, run MAVROS to put the sensors in the ROS messaging pipeline.

**Comment by a-tab-a** [comment]
Thanks for writing back prompt! So, here is what I was doing.
1) Build px4_sitl gazebo
2) Run MAVROS with roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557"
3) Launch the controller roslaunch lqr_controller lqr_euler.launch

I can see values changing in the terminal of lqr_tracker, however I don' t see that in the gazebo. I have attached the terminal window for your convenience, do you happen to what I might be doing stupid?
![px_4_lqr](https://user-images.githubusercontent.com/25964596/100651113-96f10700-330a-11eb-89af-4c22ba2433dd.png)

**Comment by llanesc** [comment]
In your PX4 terminal run: 
>> commander arm
>> commander mode offboard
This will arm the vehicle and change the mode to offboard.

**Comment by a-tab-a** [comment]
Sweet! Working! Thanks, appreciate it!
