### ISSUE TITLE
Problem towards the inner loop PID control of PX4

### ISSUE THREAD

**Issue by AllenHuangSpeedy** [llanesc/lqr-tracking#2]
Hi,
I was wondering if you just post the attitude message through the AttitudeTarget in mavros, the PID control of the inner loop in PX4 still working.
How can you ensure that LQR works in this scenerio?

Best,
Allen

**Comment by llanesc** [comment]
The attitude message is commanding body rates and collective thrust. PX4 handles the inner controller for that. If you have a question related to the theory then I recommend looking over the paper in the references.

**Comment by AllenHuangSpeedy** [comment]
> The attitude message is commanding body rates and collective thrust. PX4 handles the inner controller for that. If you have a question related to the theory then I recommend looking over the paper in the references.

That is great! Thank you!
But I still think that the controller using right now is PID+LQR since you haven't disabled the inner loop PID control.

**Comment by llanesc** [comment]
Yeah the inner loop controller is a PID controller to track body rates and thrust directly implemented in PX4. The LQR is kinematics based and treats the inputs as body rates so that the LQR commands body rates and collective thrust which the inner PID controller tracks. This is okay to do since the attitude dynamics are much faster than the position dynamics.

**Comment by AllenHuangSpeedy** [comment]
> Yeah the inner loop controller is a PID controller to track body rates and thrust directly implemented in PX4. The LQR is kinematics based and treats the inputs as body rates so that the LQR commands body rates and collective thrust which the inner PID controller tracks. This is okay to do since the attitude dynamics are much faster than the position dynamics.

Cool!!! Thank you!

**Comment by AllenHuangSpeedy** [comment]
Right, have you ever try  corrupted size vs. prev_size: 0x000000000107a520 *** when running the roslaunch lqr_controller lqr_euler.launch?

**Comment by AllenHuangSpeedy** [comment]
![image](https://user-images.githubusercontent.com/58159321/113998797-fd270100-988b-11eb-8f9e-028bdc4cc96b.png)

**Comment by llanesc** [comment]
I don't think i've ever seen that error. Do you have all the dependencies? https://github.com/ethz-adrl/control-toolbox, mavros, mav_trajectory_generation, and a few others supporting those 3?

**Comment by AllenHuangSpeedy** [comment]
> I don't think i've ever seen that error. Do you have all the dependencies? https://github.com/ethz-adrl/control-toolbox, mavros, mav_trajectory_generation, and a few others supporting those 3?

I have these 3 dependencies, but it still has this problem.
