### ISSUE TITLE
Problems on compiling

### ISSUE THREAD

**Issue by Aleksej9521** [llanesc/lqr-tracking#3]
Hi, I'm trying to compile this repo but I have some problems during catkin build: it always said to me that it cannot found blasfeo_target.h, but I have installed blasfeo. Can you help me? :)

**Comment by llanesc** [comment]
There's a lot of dependencies I never ended up putting in the README. You can find them in the package.xml file. If you still get the error, then link the picture of your terminal error. I can try to help.

**Comment by Aleksej9521** [comment]
Hi, thanks. I have a lot of errors related to dependencies with blasfeo and hpipm like this, in which the .h files are not found.
![Senza titolo](https://github.com/llanesc/lqr-tracking/assets/73386894/db6c0187-97aa-4b17-9b16-cee459fe81f5)

**Comment by llanesc** [comment]
In this project I use the [Control Toolbox](https://ethz-adrl.github.io/ct/ct_doc/doc/html/index.html). Try downloading the dependencies from https://ethz-adrl.github.io/ct/ct_doc/doc/html/install_guide.html.
Start at the top of the page and the "Optional Dependencies and Bindings" section has information for blasfeo. You'll probably need the libraries for this while includes those headers.

**Comment by Aleksej9521** [comment]
Yes, I already installed it,  in /opt directory. Do you know how to link /opt with the catkin workspace?

**Comment by llanesc** [comment]
Seems like the issue is related to the control toolbox and not my package. I don't think I ever had this issue before. What version of Ubuntu are you running? In this repo https://github.com/giaf/hpipm they mention how to install blasfeo. You can start with that.

**Comment by Aleksej9521** [comment]
I work on ubuntu 18.04. I will see on the link that you sent me, thanks.
